import logging
import json, re
from typing import List

logger = logging.getLogger('director')

from .llm_interface import chat_with_llm
from .interaction_utils import SectionInfo, SegmentGuidance, prompt_manager

def get_segment_guidance(
    user_prompt: str, 
    footage_summary: str, 
    music_info: str,
    section_info: SectionInfo,
    beats_remaining: int,
    prev_queries: List[str],
    last_query: str | None = None,
    rejection_reason: str | None = None,
    retry_count: int=3,
):
    logger.info("Generating segment guidance...")

    retrieval_query_prompt = prompt_manager.get_prompt(
        "Director", "Semantic_Query",
        user_prompt=user_prompt,
        footage_summary=footage_summary,
        music_info=music_info.split('\n', 1)[0],
        section_info=section_info,
        beats_remaining=beats_remaining,
        prev_queries='\n'.join([f"- {q}" for q in prev_queries]) if prev_queries else "None",
        prior_failure=f"# Prior Failure\nThe last retrieval query for this segment is \"{last_query}\". The video segment generated by the query was rejected because: {rejection_reason} Please further generalize the query description or switch to a different subject while keeping alignment to the section vibe.\n" if rejection_reason else ''
    )

    for attempt in range(retry_count):
        try:
            response1 = chat_with_llm([
                {"role": "user", "content": retrieval_query_prompt}
            ])
            json_match = re.search(r'\{.*\}', response1, re.DOTALL)
            if json_match:
                json_str = json_match.group(0)
            else:
                json_str = response1.strip()

            retrieval_query_json = json.loads(json_str)
            break
        except (json.JSONDecodeError, AttributeError) as e:
            print(f"Attempt {attempt + 1} failed to parse JSON: {e}")
            if attempt == retry_count - 1:
                raise ValueError("Max retries reached. Failed to get valid retrieval query from Director Agent.")

    retrieval_query = retrieval_query_json.get("retrieval_query", "")

    weight_profile_prompt = prompt_manager.get_prompt(
        "Director", "Editing_Heuristic",
        retrieval_query=retrieval_query,
        section_info=section_info,
    )
    for attempt in range(retry_count):
        try:
            response2 = chat_with_llm([
                {"role": "user", "content": weight_profile_prompt}
            ])
            json_match = re.search(r'\{.*\}', response2, re.DOTALL)
            if json_match:
                json_str = json_match.group(0)
            else:
                json_str = response2.strip()

            weight_profile_json = json.loads(json_str)
            break
        except (json.JSONDecodeError, AttributeError) as e:
            print(f"Attempt {attempt + 1} failed to parse JSON: {e}")
            if attempt == retry_count - 1:
                raise ValueError("Max retries reached. Failed to get valid weight profile from Director Agent.")
            continue

    weight_profile = weight_profile_json.get("weight_profile", "")

    pacing_control_prompt = prompt_manager.get_prompt(
        "Director", "Rhythmic_Pacing",
        user_prompt=user_prompt,
        retrieval_query=retrieval_query,
        footage_summary=footage_summary,
        music_info=music_info.split('\n', 1)[0],
        section_info=section_info,
        beats_remaining=beats_remaining,
    )
    for attempt in range(retry_count):
        try:
            response3 = chat_with_llm([
                {"role": "user", "content": pacing_control_prompt}
            ])
            json_match = re.search(r'\{.*\}', response3, re.DOTALL)
            if json_match:
                json_str = json_match.group(0)
            else:
                json_str = response3.strip()

            pacing_control_json = json.loads(json_str)
            break
        except (json.JSONDecodeError, AttributeError) as e:
            print(f"Attempt {attempt + 1} failed to parse JSON: {e}")
            if attempt == retry_count - 1:
                raise ValueError("Max retries reached. Failed to get valid pacing control from Director Agent.")
            continue

    pacing_control = pacing_control_json.get("pacing_control", [])

    guidance_profile = SegmentGuidance(
        retrieval_query=retrieval_query,
        weight_profile=weight_profile,
        pacing_control=pacing_control,
    )

    logger.info(f"Retrieval query for segment: {retrieval_query}")
    logger.info(f"weight_profile: {weight_profile}")
    logger.info(f"pacing_control: {pacing_control}")

    logger.debug(f"Director raw response: {response1}\n{response2}\n{response3}")

    return guidance_profile
